### ISSUE TITLE
ModuleNotFoundError: No module named 'layers'

### ISSUE THREAD

**Issue by arkinrc** [Beniko95J/MLF-VO#1]
Hi,
Got this error, installed layers using pip but in vain. complete error is given below;

`
File "/home/ubuntu/Music/MLF-VO/run_odometry.py", line 15, in <module>
    from third_party.monodepth2.networks import ResnetEncoder
  File "/home/ubuntu/Music/MLF-VO/third_party/monodepth2/networks/__init__.py", line 2, in <module>
    from .depth_decoder import DepthDecoder
  File "/home/ubuntu/Music/MLF-VO/third_party/monodepth2/networks/depth_decoder.py", line 14, in <module>
    from layers import *
ModuleNotFoundError: No module named 'layers'
`

Regards
arkin

**Comment by rginjapan** [comment]
@arkinrc I met the same problem, could u plz tell me how do u solve it? thanks!

**Comment by arkinrc** [comment]
> @arkinrc I met the same problem, could u plz tell me how do u solve it? thanks!

change the layers.py path from thirdparty monodepth2 or put this file into networks folder of monodepth2. Hopefully problem will be solved.

Arkin

**Comment by rginjapan** [comment]
@arkinrc Thanks for quick reply, I put all the function in layer.py to the file which `import layer`
