### ISSUE TITLE
A general question

### ISSUE THREAD

**Issue by rginjapan** [Beniko95J/MLF-VO#3]
你好，想问一个关于Channel exchange 的问题，A和B 做 CE后， 假设A变得越来越important，B越来越不important，为什么最后还是fusionA和B呢， 而不是只用A？？

**Comment by arkinrc** [comment]
> 

@rginjapan communicate only in English please, so that every can understand questions and reply accordingly.
Thanks

**Comment by rginjapan** [comment]
@arkinrc Thanks for being interested in my question, lol.
I am right now implementing CE to my framework and using this repo. as reference.
If I understand correctly, Channel Exchange will make one feature vector becomes more and more important but the other one becomes more and more meanless, why in the end of MLF-VO, it still fuse A and B together instead of using the more important feature vector. As shown in Fig2(a), after the last CE, there are still using information from both streams.

**Comment by rginjapan** [comment]
A communciation with CEN author is [here](https://github.com/yikaiw/CEN/issues/16), sorry is in Chinese @arkinrc
